export enum SalesEnum {
  afronding = "afronding",
  andere = "andere",
  bancontact = "bancontact",
  bon_pub_dll = "bon_pub_dll",
  bon_pub_lev = "bon_pub_lev",
  cash = "cash",
  cheq_spec = "cheq_spec",
  cheque_delhaize = "cheque_delhaize",
  ecocheques = "ecocheques",
  superplus = "superplus",
  elec_cadeau = "elec_cadeau",
  elec_ecocheques = "elec_ecocheques",
  elec_maaltcheq = "elec_maaltcheq",
  kadobon = "kadobon",
  kredietkaart = "kredietkaart",
  leeggoedbon = "leeggoedbon",
  maaltijdcheque = "maaltijdcheque",
  mobile = "mobile",
  online_betaling = "online_betaling",
  op_krediet = "op_krediet",
  promo = "promo",
  publiciteitsbon = "publiciteitsbon",
  tegoedbon = "tegoedbon",
  tegoedbon_crea = "tegoedbon_crea",
  terugbet_lotto = "terugbet_lotto",
  totaal = "totaal",
  totaal_lade = "totaal_lade",
}

export type Sales = {
  [key in SalesEnum]: number;
};

export const newSales = (): Sales => ({
  afronding: 0,
  andere: 0,
  bancontact: 0,
  bon_pub_dll: 0,
  bon_pub_lev: 0,
  cash: 0,
  cheq_spec: 0,
  cheque_delhaize: 0,
  ecocheques: 0,
  superplus: 0,
  elec_cadeau: 0,
  elec_ecocheques: 0,
  elec_maaltcheq: 0,
  kadobon: 0,
  kredietkaart: 0,
  leeggoedbon: 0,
  maaltijdcheque: 0,
  mobile: 0,
  online_betaling: 0,
  op_krediet: 0,
  promo: 0,
  publiciteitsbon: 0,
  tegoedbon: 0,
  tegoedbon_crea: 0,
  terugbet_lotto: 0,
  totaal: 0,
  totaal_lade: 0,
});
